<a href="https://colab.research.google.com/github/chaotiqc/mlstudies/blob/main/atividade_livro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

links uteis:
- https://scikit-learn.org/stable/modules/preprocessing.html


In [1]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv("/content/drive/MyDrive/Física - Bacharel Lic./deep learning & colisões de partículas/atividades/diabetes.csv")
#print(data.head)
array = data.values
print(array)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
# separando o array entre entrada e saida dos componentes
X = array[:,0:8]
Y = array[:, 8]
scaler = MinMaxScaler(feature_range = (0,1)) # "feature_range" :: a gama necessária de dados transformados
rescaledX = scaler.fit_transform(X) # "fit_transform" :: ajusta os dados e depois transforma-os; adapta o transformador para X e Y com parâmetros opcionais "fit_params" e depois retorna uma versão transformada de X. ### "fit_params" = parametros de ajustes adicionais.
# summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


Anotações sobre o que eu entendi de rescale:

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html


## Standardize data

In [6]:
from sklearn.preprocessing import StandardScaler
X = array[:, 0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X) ## Padrozinar caracteristicas removendo a média e escalando para a variância da unidade. ## a pontuação padrão de uma amostra x é calculado como: "z = (x-u)/s", onde "u" é a média  das amostras de treinamento ou zero e o "s" é o desvio padrão das amostras de treinamento ou um.
rescaledX = scaler.transform(X) # "transform" realiza a padronização centralizando e escalando
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler#sklearn.preprocessing.StandardScaler.transform

## Normalize Data

In [7]:
from sklearn.preprocessing import Normalizer
X = array[:, 0:8]
Y = array[:,8]
scaler = Normalizer().fit(X) ## normalizar amostras individualmente para a norma da unidade
normalizedX = scaler.transform(X)
set_printoptions(precision=3)
print(normalizedX)

[[0.034 0.828 0.403 ... 0.188 0.004 0.28 ]
 [0.008 0.716 0.556 ... 0.224 0.003 0.261]
 [0.04  0.924 0.323 ... 0.118 0.003 0.162]
 ...
 [0.027 0.651 0.388 ... 0.141 0.001 0.161]
 [0.007 0.838 0.399 ... 0.2   0.002 0.313]
 [0.008 0.736 0.554 ... 0.241 0.002 0.182]]


https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html

https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#plot-all-scaling-normalizer-section

## Binarize Data (Make Binary)

In [8]:
from sklearn.preprocessing import Binarizer
X = array[:, 0:8]
Y = array[:,8]
binarizer = Binarizer(threshold=0.0).fit(X) # Binarizar dados (defina valors de recursos para 0 ou 1) de acordo com um limite
binaryX = binarizer.transform(X)
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Binarizer.html